### ISSUE TITLE
Where is the potential source for the numerical issue?

### ISSUE THREAD

**Issue by WeihanLikk** [raphaelreme/torch-kf#1]
Thank you for your code! I compared it with my KF implementation, and it performs significantly faster. I’m curious to know which parts of your implementation contribute to its speed and whether there might be any potential numerical issues in those optimizations. Could you provide some insights?

**Comment by raphaelreme** [comment]
Hi, glad it can be useful!

The increase in speed comes mainly from 2 factors:

1.  Batch computations that allows to drop a python `for` loop.
2. Pytorch that parallelize on cpu the batch computations. (Note that the same code implemented in numpy can probably be faster when the batch is small, faster than filterpy which is already faster than torch_kf for batch < 10). The code can also be parallelized on GPU for large batch (> 5000).

In addition, I have chosen to run every computations with the default float32 of pytorch rather than the default float64 in numpy, this should increase slightly speed and decrease memory footprint, but it is less precise. But if I remember correctly, you should be able to run my code with float64 without any changes, except giving the KF object the matrices with the correct dtype.

Also, I have used the direct formula for the KF update of the covariance P =  (I - KH) P. But in filterpy, they use another more stable one (Joseph one according to rlabbe) P = (I - KH) P (I - KH)^T + KRK^T. Both formula are mathematically valid (https://github.com/rlabbe/Kalman-and-Bayesian-Filters-in-Python/blob/master/07-Kalman-Filter-Math.ipynb, in "Stable Compution of the Posterior Covariance"). I do not have the experience he had on kalman filters and I did not read the literature about these numerical issues, on my side I never experienced numerical issues for my small problems but I could probably implement in torch_kf if you are interested. This should not be so much slower.

Finally, I use a matrix `inverse` instead of a `cholesky` decomposition to inverse the innovation/projection covariance S.
I found that it was faster with smaller dimensions (usually the case in Kalman filters: the state usually have less than 10 or 100 dimensions). But it is probably a bit less stable (I do not have any sources though).

Hope this answers your questions ;)

**Comment by raphaelreme** [comment]
I re-checked the code. Indeed, you can switch to float64 easily (it is a bit slower), with kf = kf.to(torch.float64) or by constructing it directly from float64 matrices. You can check kf.dtype and kf.device to see the type and device (cpu/cuda) of your Kalman filter.

Also, inverse should be fine as in filterpy they use it too. 

And I just implemented the joseph update in torch_kf (with `joseph_update` parameter). It increase run time by 50%, and I don't see any improvements on numerical stability on my simple examples, but I'm guessing that it is indeed better.

**Comment by WeihanLikk** [comment]
Thank you for the thorough and detailed explanation!
